name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build, tag, and push Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=651706780098.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # Step 5: Download the current task definition
      - name: Download current task definition
        run: |
          aws ecs describe-task-definition --task-definition nodejs-task-def --query taskDefinition > task-definition.json

      # Step 6: Fill in the new image ID in the ECS task definition
      - name: Update ECS task definition with new image
        id: task-def
        run: |
          IMAGE_URI="651706780098.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest"
          jq '.containerDefinitions[0].image = "'$IMAGE_URI'"' task-definition.json > updated-task-definition.json
          echo "::set-output name=updated_task_def_file::updated-task-definition.json"

      # Step 7: Create AppSpec file content
      - name: Create AppSpec file content
        id: appspec
        run: |
          echo 'version: 0.0' > appspec.yml
          echo 'Resources:' >> appspec.yml
          echo '  - TargetService:' >> appspec.yml
          echo '      Type: AWS::ECS::Service' >> appspec.yml
          echo '      Properties:' >> appspec.yml
          echo '        TaskDefinition: arn:aws:ecs:us-east-1:651706780098:task-definition/nodejs-task-def:1' >> appspec.yml
          echo '        LoadBalancerInfo:' >> appspec.yml
          echo '          ContainerName: nodejs-container' >> appspec.yml
          echo '          ContainerPort: 3000' >> appspec.yml
          echo 'Hooks:' >> appspec.yml
          echo '  BeforeInstall: []' >> appspec.yml
          echo '  AfterInstall: []' >> appspec.yml
          echo '  AfterAllowTestTraffic: []' >> appspec.yml
          echo '  BeforeAllowTraffic: []' >> appspec.yml
          echo '  AfterAllowTraffic: []' >> appspec.yml
          echo "::set-output name=appspec_file_content::$(cat appspec.yml)"

      # Step 8: Deploy to ECS using CodeDeploy
      - name: Deploy to ECS using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name AppECS-Node-js-nodejs-bg \
            --deployment-group-name DgpECS-Node-js-nodejs-bg \
            --revision "{\"revisionType\":\"AppSpecContent\",\"appSpecContent\":\"${{ steps.appspec.outputs.appspec_file_content }}\"}" \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --description "Deploy new image to ECS"
